management:
  endpoints:
    web:
      expose: info, health, metrics
  server:
    port: 8010

info:
  app:
    name: kotlin test
    version: 1.0-SNAPSHOT

testService:
  proxyURI: https://www.google.com